---
csiDriver:
  # should be globally unique for a given cluster
  name: "org.democratic-csi.iscsi.okinawa"
controller:
  priorityClassName: system-cluster-critical
node:
  priorityClassName: system-node-critical
  hostPID: true
  driver:
    extraEnv:
    - name: ISCSIADM_HOST_STRATEGY
      value: nsenter
    - name: ISCSIADM_HOST_PATH
      value: /usr/local/sbin/iscsiadm
    iscsiDirHostPath: /etc/iscsi
    iscsiDirHostPathType: ""
# add note here about volume expansion requirements

storageClasses:
- name: okinawa-hdd-block
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    # for block-based storage can be ext3, ext4, xfs
    # for nfs should be nfs
    fsType: ext4
    # if true, volumes created from other snapshots will be
- name: okinawa-hdd-block-retain
  # zfs send/received instead of zfs cloned

  # detachedVolumesFromSnapshots: "false"
  # if true, volumes created from other volumes will be
  # zfs send/received instead of zfs cloned
  # detachedVolumesFromVolumes: "false"
  defaultClass: false
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    fsType: ext4
  mountOptions: []
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    #      # any arbitrary iscsiadm entries can be add by creating keys starting with node-db.<entry.name>
    #      # if doing CHAP
    #      node-db.node.session.auth.authmethod: CHAP
    #      node-db.node.session.auth.username: foo
    #      node-db.node.session.auth.password: bar
    #
    #      # if doing mutual CHAP
    #      node-db.node.session.auth.username_in: baz
    #      node-db.node.session.auth.password_in: bar
    node-publish-secret:
    controller-expand-secret:
# if your cluster supports snapshots you may enable below

volumeSnapshotClasses:
- name: okinawa-hdd-block-snapshot
  parameters:
  # if true, snapshots will be created with zfs send/receive
  # detachedSnapshots: "false"
  labels:
    velero.io/csi-volumesnapshot-class: "true"
  secrets:
    snapshotter-secret:
driver:
  config:
    # please see the most up-to-date example of the corresponding config here:
    # https://github.com/democratic-csi/democratic-csi/tree/master/examples
    # YOU MUST COPY THE DATA HERE INLINE!
    driver: freenas-api-iscsi
    instance_id: okinawa-iscsi
    httpConnection:
      # protocol: https
      # host: <injected from secret>
      # port: 443
      # use only 1 of apiKey or username/password
      # if both are present, apiKey is preferred
      # apiKey is only available starting in TrueNAS-12
      #apiKey: <injected from secret>
      # username: root
      # password:
      allowInsecure: false
      # use apiVersion 2 for TrueNAS-12 and up (will work on 11.x in some scenarios as well)
    # leave unset for auto-detection
    #apiVersion: 2
    zfs:
      # can be used to override defaults if necessary
      # the example below is useful for TrueNAS 12
      #cli:
      #  sudoEnabled: true
      #
      #  leave paths unset for auto-detection
      #  paths:
      #    zfs: /usr/local/sbin/zfs
      #    zpool: /usr/local/sbin/zpool
      #    sudo: /usr/local/bin/sudo
      #    chroot: /usr/sbin/chroot
      # can be used to set arbitrary values on the dataset/zvol
      # can use handlebars templates with the parameters from the storage class/CO
      datasetProperties:
        "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      #  "org.freenas:test": "{{ parameters.foo }}"
      #  "org.freenas:test2": "some value"
      # total volume name (zvol/<datasetParentName>/<pvc name>) length cannot exceed 63 chars
      # https://www.ixsystems.com/documentation/freenas/11.2-U5/storage.html#zfs-zvol-config-opts-tab
      # standard volume naming overhead is 46 chars
      # datasetParentName should therefore be 17 chars or less when using TrueNAS 12 or below (SCALE and 13+ do not have the same limits)
      # for work-arounds see https://github.com/democratic-csi/democratic-csi/issues/54
      datasetParentName: hdd/k8s-pw/vol
      # do NOT make datasetParentName and detachedSnapshotsDatasetParentName overlap

      # they may be siblings, but neither should be nested in the other
      # do NOT comment this option out even if you don't plan to use snapshots, just leave it with dummy value
      detachedSnapshotsDatasetParentName: hdd/k8s-pw/vol-snaps
      # "" (inherit), lz4, gzip-9, etc

      zvolCompression:
      # "" (inherit), on, off, verify
      zvolDedup:
      zvolEnableReservation: false
      # 512, 1K, 2K, 4K, 8K, 16K, 64K, 128K default is 16K

      zvolBlocksize:
    iscsi:
      targetPortal: "<injected from secret>"
      # for multipath

      targetPortals: [] # [ "server[:port]", "server[:port]", ... ]
      # leave empty to omit usage of -I with iscsiadm

      interface:
      # MUST ensure uniqueness
      # full iqn limit is 223 bytes, plan accordingly
      # default is "{{ name }}"
      #nameTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      namePrefix: k8s-pw-csi-
      nameSuffix: ""
      # add as many as needed

      targetGroups:
      # get the correct ID from the "portal" section in the UI
      # https://github.com/democratic-csi/democratic-csi/issues/302
      # NOTE: the ID in the UI does NOT always match the ID in the DB, you must use the DB value
      - targetGroupPortalGroup: 2
        # get the correct ID from the "initiators" section in the UI

        targetGroupInitiatorGroup: 5
        # None, CHAP, or CHAP Mutual

        targetGroupAuthType: None
        # get the correct ID from the "Authorized Access" section of the UI

        # only required if using Chap
        targetGroupAuthGroup:
      extentCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      extentInsecureTpc: true
      extentXenCompat: false
      extentDisablePhysicalBlocksize: true
      # 512, 1024, 2048, or 4096,

      extentBlocksize: 4096
      # "" (let FreeNAS decide, currently defaults to SSD), Unknown, SSD, 5400, 7200, 10000, 15000

      extentRpm: "SSD"
      # 0-100 (0 == ignore)

      extentAvailThreshold: 0
