---
resources:
- pangolin.yaml
images:
- name: pangolin-operator
  newName: bovfbovf/pangolin-operator
  newTag: dev-20251112-110219-b6e61e1
patches:
- patch: |
    $patch: delete
    apiVersion: v1
    kind: Namespace
    metadata:
      name: pangolin-operator-system
