---
images:
- name: ghcr.io/jorenn92/maintainerr
  newTag: 2.17.0
labels:
- pairs:
    "app.kubernetes.io/name": maintainerr
  includeTemplates: true
  includeSelectors: true
resources:
- statefulset.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
