---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocy
  namespace: home-network
  labels:
    app.kubernetes.io/name: grocy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: grocy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grocy
        preset-egress-policy: internet-only
    spec:
      restartPolicy: Always
      runtimeClassName: gvisor
      containers:
      - image: linuxserver/grocy:latest
        imagePullPolicy: IfNotPresent
        name: grocy
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Asia/Kuala_Lumpur"
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: config
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: grocy-config
