---
images:
- name: linuxserver/grocy
  newName: lscr.io/linuxserver/grocy
  newTag: version-v4.5.0
labels:
- pairs:
    "app.kubernetes.io/name": grocy
  includeTemplates: true
  includeSelectors: true
resources:
- deployment.yaml
- persistentvolumeclaim.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
