---
images:
- name: linuxserver/readarr
  newName: lscr.io/linuxserver/readarr
  newTag: develop-version-0.4.18.2805
labels:
- pairs:
    "app.kubernetes.io/name": readarr
  includeTemplates: true
  includeSelectors: true
resources:
- statefulset.yaml
- service.yaml
- httproute.yaml
- ciliumnetworkpolicy.yaml
