---
images:
- name: koenkk/zigbee2mqtt
  newTag: 2.5.0
  # newTag: latest-dev
# digest: sha256:13deb9be3a27376fe4b2ab3b296c46d666cf38c38350e54671efa1995869e8ba
resources:
- "deployment.yaml"
- "service.yaml"
- "httproute.yaml"
- "z2m-secrets.sealed.yaml"
- "pvc.yaml"
- "configmap.yaml"
commonLabels:
  app.kubernetes.io/name: zigbee2mqtt
  app.kubernetes.io/instance: sonoff-zb3-01
